### ISSUE TITLE
TODO : Firebase functions

### ISSUE THREAD

**Issue by tagazok** [tagazok/les-mirettes#1]
Request creation
- [ ] Duplicate
- [ ] Add log
- [ ] Set status to "En attente"
- [ ] Send confirmation email
- [ ] Send email to admin for validation
- [ ] Add event to calendar
- [ ] Add request to sheet

Status change
- [ ] Duplicate status
- [ ] Add log
- [ ] Send notification email
- [ ] Update event in calendar
- [ ] Update sheet (?)

**Comment by tagazok** [comment]
Event is added to calendar but with wrong days...
